### ISSUE TITLE
Missing GIF from presentation

### ISSUE THREAD

**Issue by chkoar** [MaxHalford/maxhalford.github.io#15]
I was reading your PyData presentation on Creme and I noticed that [this](https://github.com/MaxHalford/maxhalford.github.io/blob/80e34e9be2ccf71ef1da8b5da7824bd65aed00d1/content/slides/creme-pydata.html#L829) GIF no longer exists.

Cheers

**Comment by MaxHalford** [comment]
Cheers for mentioning it! I can't even remember what the GIF, so I guess we'll never know 😅. I guess next time I'll host the GIF myself!

Have a nice day.
