### ISSUE TITLE
Bishop's book is available for free at Microsoft 

### ISSUE THREAD

**Issue by alessandro-gentilini** [MaxHalford/maxhalford.github.io#19]
Hello,
I am reading your https://maxhalford.github.io/blog/bayesian-linear-regression/ and I find that Bishop's book is available for free here:
https://www.microsoft.com/en-us/research/uploads/prod/2006/01/Bishop-Pattern-Recognition-and-Machine-Learning-2006.pdf

**Comment by MaxHalford** [comment]
Hey! Very nice. Could you add that as a comment on my blog? Should be helpful for others.

**Comment by alessandro-gentilini** [comment]
@MaxHalford I tried to comment on your blog but I was not able to login. Now I succeeded!
